# Tensor Flow Basic Syntax

In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

1.8.0


In [4]:
hello = tf.constant("Hello ")

In [5]:
world = tf.constant("World")

In [6]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [9]:
print(result)

b'Hello World'


In [10]:
a = tf.constant(10)

In [11]:
b = tf.constant(20)

In [12]:
type(a)

tensorflow.python.framework.ops.Tensor

In [13]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [14]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [15]:
a + b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [16]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [17]:
print(result)

30


In [18]:
const = tf.constant(10)

In [19]:
fill_mat = tf.fill((4, 4), 10)

In [20]:
myzeros = tf.zeros((4, 4))

In [21]:
myones = tf.ones((4, 4))

In [22]:
myrandn = tf.random_normal((4, 4), mean=0, stddev=1.0)

In [23]:
myrandu = tf.random_uniform((4, 4), minval=0, maxval=1)

In [24]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [25]:
sess = tf.InteractiveSession()

In [27]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.5810828  -0.05458638  0.10300447  0.60437083]
 [-0.6534536   0.58913064 -0.6364757   0.25771347]
 [-0.8644822  -1.7381054   0.73505205 -0.126218  ]
 [-1.0930798   0.49901345  0.019401    0.6210845 ]]


[[0.08788824 0.66603243 0.97188723 0.14998353]
 [0.55393374 0.15792322 0.38891888 0.69266593]
 [0.16241801 0.32796955 0.63816583 0.39320636]
 [0.03423488 0.6903299  0.40432    0.94594705]]




In [28]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.6265677   0.73741597  0.60310924  0.88556474]
 [-0.02879854 -1.0508751   0.43403772 -0.88646185]
 [ 1.3549519  -0.1543825  -1.9718663  -0.14109746]
 [-1.7898209   0.29478994 -1.0285453   0.10342903]]


[[0.03099072 0.5867132  0.22437477 0.6463858 ]
 [0.23872077 0.08220577 0.48982418 0.33878207]
 [0.618464   0.31321752 0.8203089  0.37914956]
 [0.37836742 0.8385042  0.69712174 0.05475318]]




In [29]:
a = tf.constant([ [1, 2],
                  [3, 4] ])

In [30]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [31]:
b = tf.constant([ [10], [100]])

In [32]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [33]:
result = tf.matmul(a, b)

In [34]:
sess.run(result)

array([[210],
       [430]])

In [35]:
result.eval()

array([[210],
       [430]])

In [36]:
sess.close()